version: '3'

services:
  base: &base
    image: ghcr.io/shannon-x/chatwoot-dev:develop
    pull_policy: always
    env_file: .env
    volumes:
      - storage_data:/app/storage
    networks:
      - 1panel-network

  rails:
    <<: *base
    container_name: chatwoot-web
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always

  sidekiq:
    <<: *base
    container_name: chatwoot-sidekiq
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always

volumes:
  storage_data:

networks:
  1panel-network:
    external: true
